export const SystemConfig = {
    notificationJson: "assets/master/sys-notificaton.json",
    navigatorJson: "assets/master/navbar.json",
    faqJson: "assets/master/faq/faq.json",
    profileJson: "assets/master/profile.json",
    logoutJson: "assets/master/logout.json",
    footerJson: "assets/master/footer.json",
    albumJson: "assets/master/album.json",
    pricingJson: "assets/master/pricing.json",
    imagegallaryJson: "assets/master/imagegallary.json",
    featuretteJson: "assets/master/featurette.json",
    tableJson: "assets/master/table/table.json",
    listgroupJson: "assets/master/listgroup.json",
    mediaplayerJson: "assets/master/mediaplayer.json",
    nestednavJson: "assets/master/nestednav.json",
    tabsJson: "assets/master/tabs.json",
}